name: CI Build and Test

# Trigger the workflow for push and pull request events
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Setup Gradle https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Run Gradle build
      - name: Build with Gradle
        run: ./gradlew build

      # Run tests with Gradle
      - name: Run tests with Gradle
        run: ./gradlew test
